# These are supported funding model platforms

github: [AndroidWithRossyn]
custom: 
  - https://www.paypal.com/paypalme/banrossyn
  - https://github.com/AndroidWithRossyn/AndroidWithRossyn/blob/main/donate/upi_scan.jpg?raw=true

